- name: Exécuter la sauvegarde des VMs sur Proxmox Backup Server
  when: run_backup
  block:
    - name: Vérifier si la configuration PBS est activée
      fail:
        msg: "La configuration PBS n'est pas activée"
      when: not configurer_pbs

    - name: Lister toutes les VMs
      shell: qm list | awk '{if(NR>1)print $1}'
      register: all_vms
      when: configurer_pbs

    - name: Vérifier sauvegardes et statut de chaque VM
      block:
        - name: Vérifier si la VM a une sauvegarde sur PBS
          shell: pvesm list "{{ pbs_storage_id }}" | grep "{{ item }}" || echo "Pas de sauvegarde"
          register: backup_check
          loop: "{{ all_vms.stdout_lines }}"
          when: configurer_pbs

        - name: Vérifier si la VM est en cours d'exécution
          shell: "qm status '{{ item }}' | grep 'status: running' || echo '{{ item }} -> Déjà éteinte'"
          register: vm_running
          loop: "{{ all_vms.stdout_lines }}"
          when: configurer_pbs

    - name: Éteindre la VM si elle est allumée
      shell: "qm stop '{{ item }}'"
      when: >-
        configurer_pbs and
        "'status: running' in lookup('shell', 'qm status \"' + item + '\" | grep \"status: running\"')"
      loop: "{{ all_vms.stdout_lines }}"

    - name: Attendre que la VM soit éteinte
      shell: "qm status '{{ item }}' | grep 'status: stopped' || true"
      register: vm_stopped
      retries: 30
      delay: 10
      until: vm_stopped.rc == 0
      when: >-
        configurer_pbs and
        "'status: running' in lookup('shell', 'qm status \"' + item + '\" | grep \"status: running\"')"
      loop: "{{ all_vms.stdout_lines }}"

    - name: Effectuer la sauvegarde de la VM
      shell: vzdump "{{ item }}" --storage "{{ pbs_storage_id }}" --remove 1 --mode snapshot
      when: configurer_pbs
      with_items: "{{ all_vms.stdout_lines }}"

    - name: Redémarrer la VM
      shell: qm start "{{ item }}"
      async: 600
      poll: 0
      when: >-
        configurer_pbs and
        restart_vm_after_backup and
        (vm_running.results | selectattr('item', 'equalto', item) | map(attribute='stdout') | list | first | default('')) != 'Déjà éteinte'
      with_items: "{{ all_vms.stdout_lines }}"