- name: Exécuter la sauvegarde des VMs sur Proxmox Backup Server
  when: run_backup
  block:
    - name: Vérifier si la configuration PBS est activée
      fail:
        msg: "La configuration PBS n'est pas activée"
      when: not configurer_pbs

    - name: Lister toutes les VMs
      shell: qm list | awk '{if(NR>1)print $1}'
      register: all_vms
      when: configurer_pbs

    - name: Définir vm_is_template par défaut
      set_fact:
        vm_is_template: []

    - name: Identifier les templates VM
      shell: "qm config '{{ item }}' | grep -q 'template: 1'"
      register: vm_is_template_result
      failed_when: false
      loop: "{{ all_vms.stdout_lines }}"
      when: configurer_pbs

    - name: Mettre à jour vm_is_template avec les résultats
      set_fact:
        vm_is_template: "{{ vm_is_template_result.results }}"

    - name: Identifier les VMs non-templates
      set_fact:
        non_template_vms: "{{ all_vms.stdout_lines | difference(vm_is_template | selectattr('rc', 'equalto', 0) | map(attribute='item')) }}"
      when: configurer_pbs

    - name: Éteindre les VMs non-templates
      shell: "qm stop '{{ item }}'"
      loop: "{{ non_template_vms }}"
      when: item not in vm_is_template | map(attribute='item')
      register: vms_stopped
      ignore_errors: true

    - name: Attendre que les VMs non-templates soient éteintes
      shell: "qm status '{{ item.item }}' | grep 'status: stopped' || true"
      register: vm_stopped
      retries: 30
      delay: 10
      until: vm_stopped.rc == 0
      when: 
        - vms_stopped.results | selectattr('rc', 'defined') | list | length > 0
        - item.item not in vm_is_template | map(attribute='item')
      loop: "{{ vms_stopped.results }}"

    - name: Effectuer la sauvegarde de toutes les VMs
      shell: vzdump "{{ item }}" --storage "{{ pbs_storage_id }}" --remove 1 --mode snapshot
      when: configurer_pbs
      loop: "{{ all_vms.stdout_lines }}"

    - name: Redémarrer les VMs non-templates après la sauvegarde
      shell: qm start "{{ item }}"
      loop: "{{ non_template_vms }}"
      when: 
        - configurer_pbs
        - restart_vm_after_backup
