- name: Exécuter la sauvegarde des VMs sur Proxmox Backup Server
  when: run_backup
  block:
    - name: Vérifier si la configuration PBS est activée
      fail:
        msg: "La configuration PBS n'est pas activée"
      when: not configurer_pbs

    - name: Lister toutes les VMs
      shell: qm list | awk '{if(NR>1)print $1}'
      register: all_vms
      when: configurer_pbs

    - name: Identifier les templates VM
      shell: "qm config '{{ item }}' | grep -q 'template: 1'"
      register: vm_is_template
      failed_when: false
      loop: "{{ all_vms.stdout_lines }}"
      when: configurer_pbs

    - name: Éteindre les VMs non-templates
      shell: "qm stop '{{ item }}'"
      loop: "{{ all_vms.stdout_lines }}"
      when: 
        - configurer_pbs
        - item not in vm_is_template.results | map(attribute='item')
      ignore_errors: true

    - name: Effectuer la sauvegarde de toutes les VMs
      shell: vzdump "{{ item }}" --storage "{{ pbs_storage_id }}" --remove 1 --mode snapshot
      when: configurer_pbs
      loop: "{{ all_vms.stdout_lines }}"

    - name: Redémarrer les VMs non-templates après la sauvegarde
      shell: qm start "{{ item }}"
      loop: "{{ all_vms.stdout_lines }}"
      when: 
        - configurer_pbs
        - restart_vm_after_backup
        - item not in vm_is_template.results | map(attribute='item')
        - "'status: running' not in (lookup('ansible.builtin.shell', 'qm status ' + item)).stdout"
      ignore_errors: true
