# lets_encrypt.yml
- block:
    - name: Vérifier si un certificat Let's Encrypt est déjà en place
      shell: pvenode cert info | grep 'issuer' | grep "Let's Encrypt"
      register: lets_encrypt_cert_check
      ignore_errors: yes
      failed_when: false

    - name: Vérifier si le compte ACME existe
      shell: pvenode acme account info {{ acme_account_name }}
      register: acme_account_check
      failed_when: acme_account_check.rc == 2 # échoue si le compte n'existe pas
      ignore_errors: yes

    - name: Enregistrer le compte ACME avec Let's Encrypt si nécessaire
      expect:
        command: pvenode acme account register {{ acme_account_name }} {{ lets_encrypt_email }}
        responses:
          (?i)Enter selection: "0"
          (?i)Do you agree to the above terms\? \[y\|N\]: "y"
        timeout: 60
      when: acme_account_check.rc == 2

    - name: Configurer le domaine pour le certificat ACME
      command: pvenode config set --acme domains={{ lets_encrypt_domain }}
      when: lets_encrypt_cert_check.rc != 0

    - name: Commander le certificat Let's Encrypt si aucun certificat valide n'est présent
      command: pvenode acme cert order
      when: lets_encrypt_cert_check.rc != 0

  when: lets_encrypt_enabled
