# playbook/restore.yml
- name: Restaurer les VMs depuis le PBS si configuré
  when: run_restore
  block:
    - name: Vérifier si la configuration PBS est activée
      fail:
        msg: "La restauration PBS n'est pas configurée"
      when: not configurer_pbs

    - name: Obtenir la liste des sauvegardes de VMs depuis PBS, triée par date
      shell: pvesm list "{{ pbs_storage_id }}" | grep 'backup/vm' | sort -k5,6r
      register: sorted_vm_backup_list

    - name: Extraire la dernière sauvegarde pour chaque VM
      set_fact:
        latest_vm_backups: "{{ latest_vm_backups | default({}) | combine({ item.split(' ')[-1]: item }) }}"
      loop: "{{ sorted_vm_backup_list.stdout_lines }}"
      when: sorted_vm_backup_list.stdout_lines is defined

    - name: Afficher la liste des sauvegardes les plus récentes
      debug:
        msg: "{{ latest_vm_backups.values() }}"

    - name: Vérifier si la VM existe déjà et restaurer si nécessaire
      shell: |
        VMID="{{ item.split(' ')[-1] }}"
        BackupFile="{{ item.split(' ')[0] }}"
        if ! qm status "$VMID" > /dev/null 2>&1; then
          qmrestore "$BackupFile" "$VMID"
          if [ "{{ start_vm_after_restore }}" = "true" ]; then
            qm start "$VMID"
          fi
        else
          echo "La VM avec l'ID $VMID existe déjà, restauration ignorée."
        fi
      loop: "{{ latest_vm_backups.values() }}"
      ignore_errors: yes
